# Generated by Django 5.1.2 on 2024-10-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_room_participants_message_room_topic'),
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
    ]
